/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CropBatchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batches"
      | "createBatch"
      | "getCurrentState"
      | "nextBatchId"
      | "updateState"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BatchCreated" | "StateUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBatch",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextBatchId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateState",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextBatchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateState",
    data: BytesLike
  ): Result;
}

export namespace BatchCreatedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    farmer: AddressLike,
    cropType: string,
    location: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    farmer: string,
    cropType: string,
    location: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    farmer: string;
    cropType: string;
    location: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StateUpdatedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    newState: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    newState: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    newState: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CropBatch extends BaseContract {
  connect(runner?: ContractRunner | null): CropBatch;
  waitForDeployment(): Promise<this>;

  interface: CropBatchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint] & {
        farmer: string;
        cropType: string;
        location: string;
        state: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  createBatch: TypedContractMethod<
    [cropType: string, location: string],
    [bigint],
    "nonpayable"
  >;

  getCurrentState: TypedContractMethod<
    [batchId: BigNumberish],
    [bigint],
    "view"
  >;

  nextBatchId: TypedContractMethod<[], [bigint], "view">;

  updateState: TypedContractMethod<
    [batchId: BigNumberish, newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint] & {
        farmer: string;
        cropType: string;
        location: string;
        state: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createBatch"
  ): TypedContractMethod<
    [cropType: string, location: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCurrentState"
  ): TypedContractMethod<[batchId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextBatchId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateState"
  ): TypedContractMethod<
    [batchId: BigNumberish, newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchCreated"
  ): TypedContractEvent<
    BatchCreatedEvent.InputTuple,
    BatchCreatedEvent.OutputTuple,
    BatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StateUpdated"
  ): TypedContractEvent<
    StateUpdatedEvent.InputTuple,
    StateUpdatedEvent.OutputTuple,
    StateUpdatedEvent.OutputObject
  >;

  filters: {
    "BatchCreated(uint256,address,string,string,uint256)": TypedContractEvent<
      BatchCreatedEvent.InputTuple,
      BatchCreatedEvent.OutputTuple,
      BatchCreatedEvent.OutputObject
    >;
    BatchCreated: TypedContractEvent<
      BatchCreatedEvent.InputTuple,
      BatchCreatedEvent.OutputTuple,
      BatchCreatedEvent.OutputObject
    >;

    "StateUpdated(uint256,uint8,uint256)": TypedContractEvent<
      StateUpdatedEvent.InputTuple,
      StateUpdatedEvent.OutputTuple,
      StateUpdatedEvent.OutputObject
    >;
    StateUpdated: TypedContractEvent<
      StateUpdatedEvent.InputTuple,
      StateUpdatedEvent.OutputTuple,
      StateUpdatedEvent.OutputObject
    >;
  };
}
